[package]
name = "Zarfa_payments"
version = "1.0.0"
authors = ["Zarfa Team"]

[addresses]
Zarfa = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
